### ISSUE TITLE
Erro with makenew.sh on OSX 

### ISSUE THREAD

**Issue by silasrm** [makenew/tasty-brunch#1]
Hi,

When I'm run `makenew.sh` occurs this erro:

```
sed: 1: "13i My description": command i expects \ followed by text
```

How to solve?

**Comment by razor-x** [comment]
It's due to the differences between sed in unix and GNU sed. This will affect `makenew.sh` in the other projects too.

I don't have a Mac, but I can use FreeBSD (which should have the same behaviour) to test and fix it.

**Comment by razor-x** [comment]
@silasrm Can you test if it works for you now on the [mac-sed](https://github.com/makenew/tasty-brunch/tree/mac-sed) branch?

If so I'll update master and tag a new version.

It's working on FreeBSD, but I need to be sure it works on Mac before I update all the other scripts.

**Comment by silasrm** [comment]
Hi,

With the mac-sed branch, makenew.sh run without error 💃
