### ISSUE TITLE
How to add bootstrap and others css?

### ISSUE THREAD

**Issue by silasrm** [makenew/tasty-brunch#2]
Hi,

I'm trying to add bootstrap to my project, but nothing is added.

``` javascript
// my brunch-config.js
exports.config = {
  // npm: {
  //   styles: {
  //     'normalize.css': ['normalize.css']
  //   }
  // },

  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /^app/,
        'js/vendor.js': /^(?!app)/,
      },
      order: {
        before: [
          'jquery/dist/jquery.js',
          'dist/js/bootstrap.js',
          'moment/moment.js',
          'moment-timezone/moment-timezone.js',
          'moment-timezone/moment-timezone-utils.js'
        ]
      }
    },
    stylesheets: {
      joinTo: {
        'css/app.css': /^app/,
        'css/vendor.css': /^(?!app)/,
      },
      order: {
        before: [
          'dist/css/bootstrap.css'
        ]
      }
    }
  },

  overrides: {
    production: {
      plugins: {
        postcss: {
          processors: [
            require('autoprefixer'),
            require('cssnano')
          ]
        }
      }
    }
  },

  plugins: {
    digest: {
      prependHost: {
        production: '/'
      },
      referenceFiles: /\.(css|html|js)$/
    },

    babel: {presets: ['es2015']},

    css: {
      cssModules: true
    },

    postcss: {
      processors: [
        require('autoprefixer'),
        require('csswring')
      ]
    },

    sass: {
      modules: true,
      options: {
        includePaths: ['node_modules', 'bower_components']
      }
    },

    static: {
      processors: [
        require('html-brunch-static')({
          handlebars: {
            enableProcessor: true,
            helpers: {
              join(context, block) {
                return context.join(block.hash.delimiter)
              },
              updated_time() {
                return new Date().toISOString()
              }
            }
          }
        })
      ]
    }
  }
}
```

My bower.json

``` json
{
  "name": "xxx",
  "version": "2.0.0",
  "main": "public/js/app.js",
  "dependencies": {
    "console-polyfill": "latest",
    "jquery": "2.1.*",
    "bootstrap": "~3.3.7",
    "animate.css": "~v3.1.0",
    "moment": "~2.14.1",
    "moment-timezone": "~0.5.5"
  },
  "overrides": {
    "bootstrap": {
      "dependencies": {
        "jquery": "*"
      },
      "main": [
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    },
    "moment": {
      "main": [
        "moment.js",
        "locale/pt-br.js"
      ]
    },
    "moment-timezone": {
      "dependencies": {
        "moment": "*"
      },
      "main": [
        "moment-timezone.js",
        "moment-timezone-utils.js"
      ]
    }
  }
}
```

No vendor.css is created on public/css/ and fonts folder isn't copyed to public/. Any .css file created on vendor/ is processed. But if any .scss file is created, this is processed and vendor.css is created.

Where I'm wrong?

**Comment by razor-x** [comment]
This issue might be better and more quickly answered over on [brunch](https://github.com/brunch/brunch) as it's not really specific to this project skeleton and I don't have time at the moment to debug this right now.

I would suggest however you use npm directly and not bower, as that's what this skeleton is setup for.

Specifically, you can add global css style-sheets via this config option

``` javascript
npm: {
  styles: {
    'normalize.css': ['normalize.css']
  }
}
```

And any Sass libraries can be imported directly in you styles due to

``` javascript
sass: {
  options: {
    includePaths: ['node_modules']
  }
}
```

But you can customize that to suit your needs: https://github.com/brunch/sass-brunch#options.

Finally, for javascript, you can use the new module syntax, e.g.,

``` javascript
import jQuery from 'jquery'
```

**Comment by silasrm** [comment]
Ok.

Javascript is fine.

**Comment by silasrm** [comment]
@razor-x your gulpfile.js is strict to sass?

**Comment by razor-x** [comment]
I'm not exactly sure what you are asking, but the gulpfile does use [sass-lint](https://www.npmjs.com/package/sass-lint) via

``` js
gulp.task('sass-lint', () => {
  return gulp.src(paths.styles)
    .pipe($.sassLint())
    .pipe($.sassLint.format())
    .pipe($.sassLint.failOnError())
})
```

and

``` js
gulp.task('watch:styles', () => {
  return gulp.src(paths.styles)
    .pipe($.watch(paths.styles))
    .pipe($.plumber())
    .pipe($.sassLint())
    .pipe($.sassLint.format())
})
```

It is not configured to lint `css`, only `scss`. But since `scss` is a superset of `css` you can still write normal CSS in `scss` files and have it linted. If you don't want things linted, just remove those tasks and the other references to that task (and the devDependencies).

**Comment by silasrm** [comment]
Hi,

If I've .css, the file isn't processed in watch:styles task, correct? Because this get only .scss files.

**Comment by silasrm** [comment]
Hi,

I'm debuging with onCompile hook, results is:

```
13 Aug 00:23:48 - info: compiled 13 files into 4 files, copied 22 in 5.5 sec
public/js/vendor.js
=> bower_components/jquery/dist/jquery.js
=> node_modules/auto-reload-brunch/vendor/auto-reload.js
=> bower_components/moment/locale/pt-br.js
=> bower_components/moment/moment.js
=> bower_components/console-polyfill/index.js
=> bower_components/moment-timezone/moment-timezone-utils.js
=> bower_components/moment-timezone/moment-timezone.js
=> bower_components/bootstrap/dist/js/bootstrap.js
=> vendor/initialize.js
public/js/app.js
=> app/javascript/application.js
public/css/vendor.css
=> vendor/teste.scss
public/css/app.css
=> app/styles/main.scss
=> app/styles/variables.scss
```

But I've a file vendor/o.css and brunch don't see and process.

**Comment by razor-x** [comment]
Yes, that is correct. You can process them by updating the `styles` glob. I think something like this would work (if not try `${paths.src}/**/*.(scss|css)`).

``` js
paths = Object.assign(paths, {
  // ...
  styles: `${paths.src}/**/*.?(s)css`
})
```

Alternatively, just use the `scss` extension and write normal CSS. Every `css` file is also a valid `scss` file.

**Comment by silasrm** [comment]
I follow your change but remains the same.

In debug, when I change my vendor/o.css, don't log correctly:

```
13 Aug 00:27:44 - info: compiled in 74ms
```

But I change vendor/teste.scss the effects is other:

```
13 Aug 00:28:03 - info: compiled teste.scss into vendor.css in 435ms
public/js/vendor.js
=> node_modules/auto-reload-brunch/vendor/auto-reload.js
=> bower_components/moment/moment.js
=> bower_components/jquery/dist/jquery.js
=> bower_components/moment/locale/pt-br.js
=> bower_components/bootstrap/dist/js/bootstrap.js
=> bower_components/console-polyfill/index.js
=> bower_components/moment-timezone/moment-timezone.js
=> bower_components/moment-timezone/moment-timezone-utils.js
=> vendor/initialize.js
public/css/vendor.css
=> vendor/teste.scss
```

I'll paste this debug on my brunch issue and wait for response.

Thk's.

**Comment by razor-x** [comment]
Don't put your custom scss files into vendor, that should be reserved only for things you want to vendor (which you are unlikely to need).

Place custom scss into `app/styles`. Please refer to the demo here: https://github.com/makenew/tasty-brunch/tree/demo/app/styles

**Comment by silasrm** [comment]
This is only a test to check if brunch/skeleton compile or not the files.

**Comment by razor-x** [comment]
I think I see the issue you brought up about css not compiling. I'm looking into it. Might have something to do with the postcss plugin.

**Comment by razor-x** [comment]
Should be fixed when https://github.com/brunch/postcss-brunch/issues/17 is closed.

**Comment by silasrm** [comment]
@razor-x thank's. I'll keep an eye on this issue of postcss. :D

**Comment by razor-x** [comment]
Version 3.0.0 now uses postcss, so I am closing this issue.

**Comment by silasrm** [comment]
@razor-x thks!
